services:
    app:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
            args:
                USER_ID: ${UID}
        image: sylius/standard:1.11-traditional-alpine
        environment:
            APP_ENV: "dev"
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
        volumes:
            - ./:/app:delegated
            - ./.docker/php/php.ini:/etc/php8/php.ini:delegated
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - 80:80
        depends_on:
            - mysql
        networks:
            - sylius

    mysql:
        image: mysql:8.0
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306
        networks:
            - sylius
networks:
    sylius:
        driver: bridge
