name: "build"
on:
    push:
        branches:
            - "*.x"
    pull_request: ~
    workflow_dispatch: ~

env:
    APP_ENV: "test"
    DATABASE_URL: "mysql://root:root@127.0.0.1/sylius?serverVersion=8.0"
    PHP_EXTENSIONS: "intl, mbstring"

jobs:
    coding-standards:
        name: "Coding Standards (PHP${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.2"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    coverage: "none"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v3"
                with:
                    dependency-versions: "highest"

            -   name: "Validate composer"
                run: "composer validate --strict"

            -   name: "Check style"
                run: "vendor/bin/ecs check"

            -   name: "Rector"
                run: "vendor/bin/rector process --dry-run"

    unit-tests:
        name: "Unit tests (PHP${{ matrix.php-version }} | SF${{ matrix.symfony }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.2"
                    - "8.3"
                    - "8.4"

                symfony:
                    - "^6.4"
                    - "^7.1"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: "flex"

            -   name: "Remove sylius/sylius from composer.json"
                run: "composer remove --dev sylius/sylius --no-update --no-install"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v3"
                env:
                    SYMFONY_REQUIRE: "${{ matrix.symfony }}"
                with:
                    dependency-versions: "highest"

            -   name: "Run phpspec"
                run: "vendor/bin/phpspec run"

    integration-tests:
        name: "Integration tests (PHP${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.2"

        steps:
            -   name: "Start MySQL"
                run: "sudo /etc/init.d/mysql start"

            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    coverage: "none"

            -   name: "Setup node"
                uses: "actions/setup-node@v4"
                with:
                    node-version: "20"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v3"
                with:
                    dependency-versions: "highest"

            -   name: "Lint container"
                run: "(cd tests/TestApplication && ../../vendor/bin/console lint:container)"

            -   name: "Create database"
                run: "(cd tests/TestApplication && ../../vendor/bin/console doctrine:database:create)"

            -   name: "Create database schema"
                run: "(cd tests/TestApplication && ../../vendor/bin/console doctrine:schema:create)"

            -   name: "Validate Doctrine mapping"
                run: "(cd tests/TestApplication && ../../vendor/bin/console doctrine:schema:validate)"

    code-coverage:
        name: "Code Coverage (PHP${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.2"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP, with composer and extensions"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "pcov"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"

            -   name: "Install composer dependencies"
                uses: "ramsey/composer-install@v3"
                with:
                    dependency-versions: "highest"

            -   name: "Collect code coverage with pcov and phpunit/phpunit"
                run: "vendor/bin/phpunit --coverage-clover=.build/logs/clover.xml"

            -   name: "Send code coverage report to Codecov.io"
                uses: "codecov/codecov-action@v5"
                with:
                    token: "${{ secrets.CODECOV_TOKEN }}"
